import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import NavbarMobile from '../components/NavbarMobile';
import NavbarDesktop from '../components/NavbarDesktop';
import Footer from '../components/Footer';

const quicksand = Quicksand({ subsets: ["latin"], display: 'swap' });

export const metadata: Metadata = {
  title: "Dicoding Indonesia - Bangun Karirmu Sebagai Developer Profesional Dicoding Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={quicksand.className}>
        <header className='w-full'>
          <NavbarMobile />
          <NavbarDesktop />
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
