import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import NavbarMobile from '../components/NavbarMobile';
import NavbarDesktop from '../components/NavbarDesktop';

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dicoding Indonesia - Bangun Karirmu Sebagai Developer Profesional Dicoding Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <header className='w-full'>
          <NavbarMobile />
          <NavbarDesktop />
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
        <footer>

        </footer>
      </body>
    </html>
  );
}
